// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrbvrifufvkqffgitiuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyYnZyaWZ1ZnZrcWZmZ2l0aXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2ODY4MTQsImV4cCI6MjA4NjI2MjgxNH0.CXB5395RGqYvMhA2vTgDiZjo7p3Fa_Qza9-uRySAmC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});